import type { PlacedPhoto } from "@/lib/media";

const addedAt = "2026-09-13T00:00:00.000Z";

export const machinePhotoArchive: PlacedPhoto[] = [
  {
    id: "machine-f150-overlook",
    storagePath: "local/f150-overlook.jpg",
    url: "/images/hobbies/machines/f150-overlook.jpg",
    page: "who-i-am",
    slot: "being-drive",
    alt: "Silver Ford F-150 Tremor parked at a mountain overlook",
    caption: "A mountain overlook.",
    sortOrder: 0,
    createdAt: addedAt,
  },
  {
    id: "machine-f150-trail-front",
    storagePath: "local/f150-trail-front.jpg",
    url: "/images/hobbies/machines/f150-trail-front.jpg",
    page: "who-i-am",
    slot: "being-drive",
    alt: "Dusty silver Ford F-150 Tremor on a forest trail",
    caption: "Trail dust across the windshield.",
    sortOrder: 1,
    createdAt: addedAt,
  },
  {
    id: "machine-f150-rocky-trail",
    storagePath: "local/f150-rocky-trail.jpg",
    url: "/images/hobbies/machines/f150-rocky-trail.jpg",
    page: "who-i-am",
    slot: "being-drive",
    alt: "Rear view of a silver Ford F-150 Tremor on a rocky trail through trees",
    caption: "A rocky stretch through the trees.",
    sortOrder: 2,
    createdAt: addedAt,
  },
  {
    id: "machine-f150-evening",
    storagePath: "local/f150-evening.jpg",
    url: "/images/hobbies/machines/f150-evening.jpg",
    page: "who-i-am",
    slot: "being-drive",
    alt: "Rear view of a silver Ford F-150 Tremor in warm evening light",
    caption: "Evening light on the Tremor.",
    sortOrder: 3,
    createdAt: addedAt,
  },
  {
    id: "machine-f150-sunset",
    storagePath: "local/f150-sunset.jpg",
    url: "/images/hobbies/machines/f150-sunset.jpg",
    page: "who-i-am",
    slot: "being-drive",
    alt: "Silver Ford F-150 Tremor beneath a red and blue sunset",
    caption: "After sunset, tail lamps on.",
    sortOrder: 4,
    createdAt: addedAt,
  },
  {
    id: "machine-f150-under-trees",
    storagePath: "local/f150-under-trees.jpg",
    url: "/images/hobbies/machines/f150-under-trees.jpg",
    page: "who-i-am",
    slot: "being-drive",
    alt: "Silver Ford F-150 Tremor parked beneath a large tree",
    caption: "Parked beneath the trees.",
    sortOrder: 5,
    createdAt: addedAt,
  },
  {
    id: "machine-f150-clear-sky",
    storagePath: "local/f150-clear-sky.jpg",
    url: "/images/hobbies/machines/f150-clear-sky.jpg",
    page: "who-i-am",
    slot: "being-drive",
    alt: "Front view of a silver Ford F-150 Tremor under a clear blue sky",
    caption: "A clear-sky front view.",
    sortOrder: 6,
    createdAt: addedAt,
  },
];

export const cubePhotoArchive: PlacedPhoto[] = [
  {
    id: "cube-gan-christmas",
    storagePath: "local/gan-christmas.jpg",
    url: "/images/hobbies/cubes/gan-christmas.jpg",
    page: "who-i-am",
    slot: "being-cubes",
    alt: "Pink-framed GAN speed cube in front of a red Santa hat",
    caption: "Holiday scramble.",
    sortOrder: 0,
    createdAt: addedAt,
  },
  {
    id: "cube-collection",
    storagePath: "local/collection.jpg",
    url: "/images/hobbies/cubes/collection.jpg",
    page: "who-i-am",
    slot: "being-cubes",
    alt: "Assorted twisty puzzles scattered on a bed sheet",
    caption: "The wider collection.",
    sortOrder: 1,
    createdAt: addedAt,
  },
  {
    id: "cube-tennis-court-dusk",
    storagePath: "local/tennis-court-dusk.jpg",
    url: "/images/hobbies/cubes/tennis-court-dusk.jpg",
    page: "who-i-am",
    slot: "being-cubes",
    alt: "Hand holding a scrambled cube at a tennis court gate at dusk",
    caption: "Courtside, after practice.",
    sortOrder: 2,
    createdAt: addedAt,
  },
];
